version: "3"
services:
   mymongo:
     image: mongo 
     ports:
       - "27017:27017"
     volumes:
       - db:/data/db
   nodeapp:
     build: .
     ports:
       - "8000:6000"
     depends_on:
       - mymongo
volumes:
  db:
   
